"""initial schema

Revision ID: 4a39dc767be2
Revises:
Create Date: 2026-09-10 10:45:23.634817

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a39dc767be2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "controls",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("factor", sa.String(length=32), nullable=False),
        sa.Column("effectiveness", sa.Float(), nullable=True),
        sa.Column(
            "applies_to_assets",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_controls_effectiveness"), "controls", ["effectiveness"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sector", sa.String(length=120), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "framework_scope",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vulnerabilities",
        sa.Column("cve_id", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("published", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=True),
        sa.Column("cvss_version", sa.String(length=8), nullable=True),
        sa.Column("cvss_base_score", sa.Float(), nullable=True),
        sa.Column("cvss_severity", sa.String(length=16), nullable=True),
        sa.Column("cvss_vector", sa.String(length=255), nullable=True),
        sa.Column(
            "cwes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "affected_cpe",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("epss", sa.Float(), nullable=True),
        sa.Column("epss_percentile", sa.Float(), nullable=True),
        sa.Column("epss_date", sa.Date(), nullable=True),
        sa.Column("kev", sa.Boolean(), nullable=False),
        sa.Column("kev_date_added", sa.Date(), nullable=True),
        sa.Column("kev_due_date", sa.Date(), nullable=True),
        sa.Column("kev_ransomware", sa.Boolean(), nullable=False),
        sa.Column("kev_required_action", sa.Text(), nullable=True),
        sa.Column(
            "attack_techniques",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "references",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "sources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("cve_id"),
    )
    op.create_index(
        op.f("ix_vulnerabilities_cvss_base_score"),
        "vulnerabilities",
        ["cvss_base_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerabilities_cvss_severity"), "vulnerabilities", ["cvss_severity"], unique=False
    )
    op.create_index(op.f("ix_vulnerabilities_epss"), "vulnerabilities", ["epss"], unique=False)
    op.create_index(op.f("ix_vulnerabilities_kev"), "vulnerabilities", ["kev"], unique=False)
    op.create_table(
        "business_units",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("criticality", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_business_units_organization_id"),
        "business_units",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "control_evidence",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("control_id", sa.String(length=64), nullable=False),
        sa.Column("coverage", sa.Float(), nullable=True),
        sa.Column("configuration_strength", sa.Float(), nullable=True),
        sa.Column("policy_compliance", sa.Float(), nullable=True),
        sa.Column("recent_incident_signal", sa.Float(), nullable=True),
        sa.Column("verification_age_days", sa.Integer(), nullable=True),
        sa.Column("measured_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["control_id"], ["controls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_control_evidence_control_id"), "control_evidence", ["control_id"], unique=False
    )
    op.create_table(
        "services",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("business_unit_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("revenue_dependency", sa.Integer(), nullable=True),
        sa.Column("regulatory_scope", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["business_unit_id"], ["business_units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_services_business_unit_id"), "services", ["business_unit_id"], unique=False
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("service_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("owner", sa.String(length=120), nullable=True),
        sa.Column("internet_exposed", sa.Boolean(), nullable=False),
        sa.Column("rto_hours", sa.Float(), nullable=True),
        sa.Column(
            "criticality",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("criticality_score", sa.Float(), nullable=True),
        sa.Column("criticality_band", sa.String(length=16), nullable=True),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assets_criticality_band"), "assets", ["criticality_band"], unique=False
    )
    op.create_index(
        op.f("ix_assets_criticality_score"), "assets", ["criticality_score"], unique=False
    )
    op.create_index(op.f("ix_assets_service_id"), "assets", ["service_id"], unique=False)
    op.create_table(
        "findings",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("cve_id", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("raw_severity", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("detected_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["cve_id"], ["vulnerabilities.cve_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_asset_id"), "findings", ["asset_id"], unique=False)
    op.create_index(op.f("ix_findings_cve_id"), "findings", ["cve_id"], unique=False)
    op.create_table(
        "scenarios",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("asset_id", sa.String(length=64), nullable=True),
        sa.Column("service_id", sa.String(length=64), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "attack_techniques",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "cve_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "spec",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scenarios_asset_id"), "scenarios", ["asset_id"], unique=False)
    op.create_index(op.f("ix_scenarios_service_id"), "scenarios", ["service_id"], unique=False)
    op.create_table(
        "simulations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scenario_id", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("n_trials", sa.Integer(), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=True),
        sa.Column("eal", sa.Float(), nullable=True),
        sa.Column("p50", sa.Float(), nullable=True),
        sa.Column("p90", sa.Float(), nullable=True),
        sa.Column("p95", sa.Float(), nullable=True),
        sa.Column("p99", sa.Float(), nullable=True),
        sa.Column("cvar_95", sa.Float(), nullable=True),
        sa.Column("vulnerability", sa.Float(), nullable=True),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scenario_id"], ["scenarios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_simulations_input_hash"), "simulations", ["input_hash"], unique=False)
    op.create_index(
        op.f("ix_simulations_scenario_id"), "simulations", ["scenario_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_simulations_scenario_id"), table_name="simulations")
    op.drop_index(op.f("ix_simulations_input_hash"), table_name="simulations")
    op.drop_table("simulations")
    op.drop_index(op.f("ix_scenarios_service_id"), table_name="scenarios")
    op.drop_index(op.f("ix_scenarios_asset_id"), table_name="scenarios")
    op.drop_table("scenarios")
    op.drop_index(op.f("ix_findings_cve_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_asset_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_assets_service_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_criticality_score"), table_name="assets")
    op.drop_index(op.f("ix_assets_criticality_band"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_services_business_unit_id"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_control_evidence_control_id"), table_name="control_evidence")
    op.drop_table("control_evidence")
    op.drop_index(op.f("ix_business_units_organization_id"), table_name="business_units")
    op.drop_table("business_units")
    op.drop_index(op.f("ix_vulnerabilities_kev"), table_name="vulnerabilities")
    op.drop_index(op.f("ix_vulnerabilities_epss"), table_name="vulnerabilities")
    op.drop_index(op.f("ix_vulnerabilities_cvss_severity"), table_name="vulnerabilities")
    op.drop_index(op.f("ix_vulnerabilities_cvss_base_score"), table_name="vulnerabilities")
    op.drop_table("vulnerabilities")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_controls_effectiveness"), table_name="controls")
    op.drop_table("controls")
    # ### end Alembic commands ###
